</$objtype/mkfile

TARG=7l
OFILES=\
	asm.$O\
	asmout.$O\
	list.$O\
	noop.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	enam.$O\
	compat.$O\
	elf.$O\

HFILES=\
	l.h\
	../7c/7.out.h\
	../8l/elf.h\

BIN=/$objtype/bin
CFLAGS=$CFLAGS -. -I.
</sys/src/cmd/mkone

../7c/enam.c: ../7c/7.out.h
	@ { cd ../7c; mk enam.c }

enam.$O:	../7c/enam.c
	$CC $CFLAGS ../7c/enam.c
elf.$O:	../8l/elf.c
	$CC $CFLAGS ../8l/elf.c

x:V:	$O.out
	$O.out -la -o/dev/null x.7
